# Generated by Django 3.2.4 on 2021-06-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default=1, max_length=25, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.TextField(default=2, max_length=25, verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
